// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6jrHib0GKKHRrxTBGivLfoZHcAGJDBwA',
    appId: '1:76177894884:web:e360725bc739faf9c8abf1',
    messagingSenderId: '76177894884',
    projectId: 'feast-c9ec5',
    authDomain: 'feast-c9ec5.firebaseapp.com',
    storageBucket: 'feast-c9ec5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARgSop8tg3UpAo7_Zq3zj18ApnOYcHVHI',
    appId: '1:76177894884:android:ed0d413d9ed2961dc8abf1',
    messagingSenderId: '76177894884',
    projectId: 'feast-c9ec5',
    storageBucket: 'feast-c9ec5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYRu-mhFRa4YQNW0WzDy9uAthdq-aI6OE',
    appId: '1:76177894884:ios:aa2f8bda75a4a58ac8abf1',
    messagingSenderId: '76177894884',
    projectId: 'feast-c9ec5',
    storageBucket: 'feast-c9ec5.firebasestorage.app',
    iosBundleId: 'com.example.feast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYRu-mhFRa4YQNW0WzDy9uAthdq-aI6OE',
    appId: '1:76177894884:ios:aa2f8bda75a4a58ac8abf1',
    messagingSenderId: '76177894884',
    projectId: 'feast-c9ec5',
    storageBucket: 'feast-c9ec5.firebasestorage.app',
    iosBundleId: 'com.example.feast',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6jrHib0GKKHRrxTBGivLfoZHcAGJDBwA',
    appId: '1:76177894884:web:fa58d16181a8b9bbc8abf1',
    messagingSenderId: '76177894884',
    projectId: 'feast-c9ec5',
    authDomain: 'feast-c9ec5.firebaseapp.com',
    storageBucket: 'feast-c9ec5.firebasestorage.app',
  );

}